### ISSUE TITLE
ValueError: could not convert string to float - "short version" example

### ISSUE THREAD

**Issue by audreyr** [django/djangobench#25]
When I follow the "short version" example, I get this error:

```
$ djangobench --control=1.2 --experiment=master
Running all benchmarks
Control: Django 1.2 (in git branch 1.2)
Experiment: Django 1.9.dev20150415021140 (in git branch master)

Running 'default_middleware' benchmark ...
Traceback (most recent call last):
  File "/Users/audreyr/.virtualenvs/experiments/bin/djangobench", line 8, in <module>
    load_entry_point('djangobench==0.10', 'console_scripts', 'djangobench')()
  File "/Users/audreyr/code/third-party/djangobench/djangobench/main.py", line 397, in main
    experiment_python=args.experiment_python,
  File "/Users/audreyr/code/third-party/djangobench/djangobench/main.py", line 73, in run_benchmarks
    env=control_env)
  File "/Users/audreyr/code/third-party/djangobench/djangobench/main.py", line 145, in run_benchmark
    data_points = [float(line) for line in message.get_payload().splitlines()]
ValueError: could not convert string to float: d
```

**Comment by audreyr** [comment]
I get the same error for these as well, just FYI:

```
djangobench --control=1.7 --experiment=master
djangobench --control=1.8 --experiment=master
```

**Comment by mjtamlyn** [comment]
Seems to work fine for me. Python 3 bug maybe?

**Comment by timgraham** [comment]
I encountered this error if a benchmark outputs something to stdout, such as if you add a print statement for debugging.
